name: Проверка репозитория
on: [push]
jobs:
  tests:
    name: Тесты скриптов
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Главный тест скрипта
      run: |
        chmod +x test_todo.sh
        chmod +x main.sh
        ./test_todo.sh
